apiVersion: v1
kind: Service
metadata:
  name: {{ include "mysqlapp.fullname" . }}
  labels:
    {{- include "mysqlapp.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      port: 3000
      targetPort: 3000
      nodePort: 30001
  selector:
    {{- include "mysqlapp.selectorLabels" . | nindent 4 }}
